/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telatrilha;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Joamila
 * Created: 14/02/2016
 * Last Modified: 26/02/2016
 */
public class JogoTrilha extends javax.swing.JFrame {
    
    /**
     * Creates new form JogoTrilha
     */
    public JogoTrilha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPanel = new javax.swing.JPanel();
        barraMenusPanel = new javax.swing.JPanel();
        voltarJogoButton = new javax.swing.JButton();
        iniciarJogoButton = new javax.swing.JButton();
        desistirJogoButton = new javax.swing.JButton();
        reiniciarJogoButton = new javax.swing.JButton();
        chatPanel = new javax.swing.JPanel();
        conversaScrollPane = new javax.swing.JScrollPane();
        conversaTextArea = new javax.swing.JTextArea();
        enviarButton = new javax.swing.JButton();
        tituloChatLabel = new javax.swing.JLabel();
        mensagemTextField = new javax.swing.JTextField();
        statusJogoPanel = new javax.swing.JPanel();
        statusJogoLabel = new javax.swing.JLabel();
        tabuleiroPanelImagem = new componentes.UJPanelImagem();
        a1Label = new javax.swing.JLabel();
        a2Label = new javax.swing.JLabel();
        a3Label = new javax.swing.JLabel();
        b3Label = new javax.swing.JLabel();
        b2Label = new javax.swing.JLabel();
        b1Label = new javax.swing.JLabel();
        d2Label = new javax.swing.JLabel();
        c1Label = new javax.swing.JLabel();
        d3Label = new javax.swing.JLabel();
        f1Label = new javax.swing.JLabel();
        c2Label = new javax.swing.JLabel();
        c3Label = new javax.swing.JLabel();
        e2Label = new javax.swing.JLabel();
        d4Label = new javax.swing.JLabel();
        e3Label = new javax.swing.JLabel();
        d5Label = new javax.swing.JLabel();
        d6Label = new javax.swing.JLabel();
        e1Label = new javax.swing.JLabel();
        g2Label = new javax.swing.JLabel();
        f2Label = new javax.swing.JLabel();
        f3Label = new javax.swing.JLabel();
        g1Label = new javax.swing.JLabel();
        d1Label = new javax.swing.JLabel();
        g3Label = new javax.swing.JLabel();
        caixaPecasPanel = new javax.swing.JPanel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        p4Label = new javax.swing.JLabel();
        p5Label = new javax.swing.JLabel();
        p6Label = new javax.swing.JLabel();
        p7Label = new javax.swing.JLabel();
        p8Label = new javax.swing.JLabel();
        p9Label = new javax.swing.JLabel();
        selecaoPecaPanel = new javax.swing.JPanel();
        selecaPecaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trilha - by Joamila Brito");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        telaPanel.setBackground(new java.awt.Color(204, 255, 204));
        telaPanel.setForeground(new java.awt.Color(0, 0, 204));

        barraMenusPanel.setBackground(new java.awt.Color(204, 255, 204));
        barraMenusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        voltarJogoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        voltarJogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telatrilha/voltar.png"))); // NOI18N
        voltarJogoButton.setText("Voltar");
        voltarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarJogoButtonActionPerformed(evt);
            }
        });

        iniciarJogoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iniciarJogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telatrilha/iniciar.png"))); // NOI18N
        iniciarJogoButton.setText("Iniciar");
        iniciarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJogoButtonActionPerformed(evt);
            }
        });
        iniciarJogoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iniciarJogoButtonKeyPressed(evt);
            }
        });

        desistirJogoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desistirJogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telatrilha/desistir.png"))); // NOI18N
        desistirJogoButton.setText("Desistir");
        desistirJogoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desistirJogoButtonMouseClicked(evt);
            }
        });
        desistirJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desistirJogoButtonActionPerformed(evt);
            }
        });

        reiniciarJogoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reiniciarJogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telatrilha/reiniciar.png"))); // NOI18N
        reiniciarJogoButton.setText("Reiniciar");
        reiniciarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarJogoButtonActionPerformed(evt);
            }
        });
        reiniciarJogoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reiniciarJogoButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout barraMenusPanelLayout = new javax.swing.GroupLayout(barraMenusPanel);
        barraMenusPanel.setLayout(barraMenusPanelLayout);
        barraMenusPanelLayout.setHorizontalGroup(
            barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(barraMenusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iniciarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, barraMenusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desistirJogoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarJogoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciarJogoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraMenusPanelLayout.setVerticalGroup(
            barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraMenusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(reiniciarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(desistirJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chatPanel.setBackground(new java.awt.Color(204, 255, 204));
        chatPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        conversaTextArea.setEditable(false);
        conversaTextArea.setColumns(20);
        conversaTextArea.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        conversaTextArea.setLineWrap(true);
        conversaTextArea.setRows(5);
        conversaTextArea.setWrapStyleWord(true);
        conversaScrollPane.setViewportView(conversaTextArea);
        conversaTextArea.getAccessibleContext().setAccessibleName("public");

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        enviarButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enviarButtonKeyPressed(evt);
            }
        });

        tituloChatLabel.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        tituloChatLabel.setForeground(new java.awt.Color(0, 102, 0));
        tituloChatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloChatLabel.setText("Bem vind@ ao chat Trilha!");
        tituloChatLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        mensagemTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mensagemTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mensagemTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensagemTextField)
                    .addComponent(conversaScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloChatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloChatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conversaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        statusJogoPanel.setBackground(new java.awt.Color(204, 255, 204));
        statusJogoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        statusJogoLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        javax.swing.GroupLayout statusJogoPanelLayout = new javax.swing.GroupLayout(statusJogoPanel);
        statusJogoPanel.setLayout(statusJogoPanelLayout);
        statusJogoPanelLayout.setHorizontalGroup(
            statusJogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusJogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusJogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusJogoPanelLayout.setVerticalGroup(
            statusJogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusJogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusJogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabuleiroPanelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));
        tabuleiroPanelImagem.setImagem(new java.io.File("C:\\Users\\Joamila\\Dropbox\\IFCE\\S9\\PPD\\Trabalho01\\TelaTrilha\\src\\telatrilha\\tabuleiro.png"));
        tabuleiroPanelImagem.setPreferredSize(new java.awt.Dimension(0, 0));

        a1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a1LabelMouseExited(evt);
            }
        });

        a2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a2LabelMouseExited(evt);
            }
        });

        a3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a3LabelMouseExited(evt);
            }
        });

        b3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3LabelMouseExited(evt);
            }
        });

        b2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2LabelMouseExited(evt);
            }
        });

        b1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1LabelMouseExited(evt);
            }
        });

        d2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d2LabelMouseExited(evt);
            }
        });

        c1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1LabelMouseExited(evt);
            }
        });

        d3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d3LabelMouseExited(evt);
            }
        });

        f1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f1LabelMouseExited(evt);
            }
        });

        c2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c2LabelMouseExited(evt);
            }
        });

        c3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c3LabelMouseExited(evt);
            }
        });

        e2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e2LabelMouseExited(evt);
            }
        });

        d4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d4LabelMouseExited(evt);
            }
        });

        e3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e3LabelMouseExited(evt);
            }
        });

        d5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d5LabelMouseExited(evt);
            }
        });

        d6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d6LabelMouseExited(evt);
            }
        });
        d6Label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                d6LabelFocusGained(evt);
            }
        });

        e1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e1LabelMouseExited(evt);
            }
        });

        g2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                g2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                g2LabelMouseExited(evt);
            }
        });

        f2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f2LabelMouseExited(evt);
            }
        });

        f3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f3LabelMouseExited(evt);
            }
        });

        g1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                g1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                g1LabelMouseExited(evt);
            }
        });

        d1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d1LabelMouseExited(evt);
            }
        });

        g3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                g3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                g3LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tabuleiroPanelImagemLayout = new javax.swing.GroupLayout(tabuleiroPanelImagem);
        tabuleiroPanelImagem.setLayout(tabuleiroPanelImagemLayout);
        tabuleiroPanelImagemLayout.setHorizontalGroup(
            tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(g1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(a1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                    .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(c1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(d3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                            .addComponent(e1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(e2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(e3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabuleiroPanelImagemLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(f2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(103, 103, 103)))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(d4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(b1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addComponent(b3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(c2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(c3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g3Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        tabuleiroPanelImagemLayout.setVerticalGroup(
            tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(a2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(d1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(g1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(d4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(d3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d5Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d6Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(e1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(f1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(g2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        caixaPecasPanel.setBackground(new java.awt.Color(204, 255, 204));
        caixaPecasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        p2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p2LabelMouseExited(evt);
            }
        });

        p3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p3LabelMouseExited(evt);
            }
        });

        p1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1LabelMouseExited(evt);
            }
        });

        p4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p4LabelMouseExited(evt);
            }
        });

        p5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p5LabelMouseExited(evt);
            }
        });

        p6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p6LabelMouseExited(evt);
            }
        });

        p7Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p7LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p7LabelMouseExited(evt);
            }
        });

        p8Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p8LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p8LabelMouseExited(evt);
            }
        });

        p9Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p9LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p9LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p9LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout caixaPecasPanelLayout = new javax.swing.GroupLayout(caixaPecasPanel);
        caixaPecasPanel.setLayout(caixaPecasPanelLayout);
        caixaPecasPanelLayout.setHorizontalGroup(
            caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, caixaPecasPanelLayout.createSequentialGroup()
                        .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                        .addComponent(p3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                        .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(p9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        caixaPecasPanelLayout.setVerticalGroup(
            caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                        .addComponent(p3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                        .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selecaoPecaPanel.setBackground(new java.awt.Color(204, 255, 204));
        selecaoPecaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), null));

        selecaPecaLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        selecaPecaLabel.setForeground(new java.awt.Color(0, 102, 0));
        selecaPecaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout selecaoPecaPanelLayout = new javax.swing.GroupLayout(selecaoPecaPanel);
        selecaoPecaPanel.setLayout(selecaoPecaPanelLayout);
        selecaoPecaPanelLayout.setHorizontalGroup(
            selecaoPecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaPecaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        selecaoPecaPanelLayout.setVerticalGroup(
            selecaoPecaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPecaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaPecaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout telaPanelLayout = new javax.swing.GroupLayout(telaPanel);
        telaPanel.setLayout(telaPanelLayout);
        telaPanelLayout.setHorizontalGroup(
            telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPanelLayout.createSequentialGroup()
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusJogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabuleiroPanelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caixaPecasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraMenusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(selecaoPecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaPanelLayout.setVerticalGroup(
            telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPanelLayout.createSequentialGroup()
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabuleiroPanelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(telaPanelLayout.createSequentialGroup()
                        .addComponent(barraMenusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixaPecasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusJogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selecaoPecaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(telaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(telaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void a1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseClicked

    private void a2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseClicked

    private void a3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseClicked

    private void voltarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarJogoButtonActionPerformed

    private void iniciarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarJogoButtonActionPerformed

    private void iniciarJogoButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iniciarJogoButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarJogoButtonKeyPressed

    private void d6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseExited

    private void d6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseClicked

    private void d6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseEntered

    private void d6LabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d6LabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelFocusGained

    private void a1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseEntered

    private void a1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseExited

    private void a2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseEntered

    private void a2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseExited

    private void a3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseEntered

    private void a3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseExited

    private void b1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseClicked

    private void b1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseEntered

    private void b1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseExited

    private void b2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseClicked

    private void b2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseEntered

    private void b2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseExited

    private void b3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseClicked

    private void b3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseEntered

    private void b3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseExited

    private void c1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseClicked

    private void c1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseEntered

    private void c1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseExited

    private void c2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseClicked

    private void c2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseEntered

    private void c2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseExited

    private void c3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseClicked

    private void c3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseEntered

    private void c3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseExited

    private void d1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseClicked

    private void d1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseEntered

    private void d1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseExited

    private void d2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseClicked

    private void d2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseEntered

    private void d2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseExited

    private void d3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseEntered

    private void d3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseClicked

    private void d3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseExited

    private void d4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseClicked

    private void d4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseEntered

    private void d4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseExited

    private void d5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseClicked

    private void d5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseEntered

    private void d5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseExited

    private void e1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseClicked

    private void e1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseEntered

    private void e1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseExited

    private void e2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseClicked

    private void e2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseEntered

    private void e2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseExited

    private void e3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseClicked

    private void e3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseEntered

    private void e3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseExited

    private void f1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseClicked

    private void f1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseEntered

    private void f1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseExited

    private void f2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseClicked

    private void f2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseEntered

    private void f2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseExited

    private void f3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseClicked

    private void f3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseEntered

    private void f3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseExited

    private void g1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_g1LabelMouseClicked

    private void g1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_g1LabelMouseEntered

    private void g1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_g1LabelMouseExited

    private void g2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_g2LabelMouseClicked

    private void g2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_g2LabelMouseEntered

    private void g2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_g2LabelMouseExited

    private void g3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_g3LabelMouseClicked

    private void g3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_g3LabelMouseEntered

    private void g3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_g3LabelMouseExited

    private void p1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseClicked

    private void p1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseEntered

    private void p1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseExited

    private void p2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseClicked

    private void p2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseEntered

    private void p2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseExited

    private void p3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseClicked

    private void p3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseExited

    private void p3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseEntered

    private void p4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseClicked

    private void p4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseEntered

    private void p4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseExited

    private void p5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseClicked

    private void p5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseEntered

    private void p5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseExited

    private void p6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseClicked

    private void p6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseEntered

    private void p6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseExited

    private void p7LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseClicked

    private void p7LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseEntered

    private void p7LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseExited

    private void p8LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseClicked

    private void p8LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseEntered

    private void p8LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseExited

    private void p9LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p9LabelMouseClicked

    private void p9LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p9LabelMouseEntered

    private void p9LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p9LabelMouseExited

    private void reiniciarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reiniciarJogoButtonActionPerformed

    private void desistirJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desistirJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desistirJogoButtonActionPerformed

    private void desistirJogoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desistirJogoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_desistirJogoButtonMouseClicked

    private void reiniciarJogoButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reiniciarJogoButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reiniciarJogoButtonKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void mensagemTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensagemTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemTextFieldKeyPressed

    private void enviarButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviarButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTrilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTrilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTrilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTrilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoTrilha().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1Label;
    private javax.swing.JLabel a2Label;
    private javax.swing.JLabel a3Label;
    private javax.swing.JLabel b1Label;
    private javax.swing.JLabel b2Label;
    private javax.swing.JLabel b3Label;
    private javax.swing.JPanel barraMenusPanel;
    private javax.swing.JLabel c1Label;
    private javax.swing.JLabel c2Label;
    private javax.swing.JLabel c3Label;
    private javax.swing.JPanel caixaPecasPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JScrollPane conversaScrollPane;
    public javax.swing.JTextArea conversaTextArea;
    private javax.swing.JLabel d1Label;
    private javax.swing.JLabel d2Label;
    private javax.swing.JLabel d3Label;
    private javax.swing.JLabel d4Label;
    private javax.swing.JLabel d5Label;
    private javax.swing.JLabel d6Label;
    private javax.swing.JButton desistirJogoButton;
    private javax.swing.JLabel e1Label;
    private javax.swing.JLabel e2Label;
    private javax.swing.JLabel e3Label;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel f1Label;
    private javax.swing.JLabel f2Label;
    private javax.swing.JLabel f3Label;
    private javax.swing.JLabel g1Label;
    private javax.swing.JLabel g2Label;
    private javax.swing.JLabel g3Label;
    private javax.swing.JButton iniciarJogoButton;
    private javax.swing.JTextField mensagemTextField;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JLabel p5Label;
    private javax.swing.JLabel p6Label;
    private javax.swing.JLabel p7Label;
    private javax.swing.JLabel p8Label;
    private javax.swing.JLabel p9Label;
    private javax.swing.JButton reiniciarJogoButton;
    private javax.swing.JLabel selecaPecaLabel;
    private javax.swing.JPanel selecaoPecaPanel;
    private javax.swing.JLabel statusJogoLabel;
    private javax.swing.JPanel statusJogoPanel;
    private componentes.UJPanelImagem tabuleiroPanelImagem;
    private javax.swing.JPanel telaPanel;
    private javax.swing.JLabel tituloChatLabel;
    private javax.swing.JButton voltarJogoButton;
    // End of variables declaration//GEN-END:variables

    public JLabel getA1Label(){ return a1Label; }
    public JLabel getA2Label(){ return a2Label; }
    public JLabel getA3Label(){ return a3Label; }
    public JLabel getB1Label(){ return b1Label; }
    public JLabel getB2Label(){ return b2Label; }
    public JLabel getB3Label(){ return b3Label; }
    public JLabel getC1Label(){ return c1Label; }
    public JLabel getC2Label(){ return c2Label; }
    public JLabel getC3Label(){ return c3Label; }
    public JLabel getD1Label(){ return d1Label; }
    public JLabel getD2Label(){ return d2Label; }
    public JLabel getD3Label(){ return d3Label; }
    public JLabel getD4Label(){ return d4Label; }
    public JLabel getD5Label(){ return d5Label; }
    public JLabel getD6Label(){ return d6Label; }
    public JLabel getE1Label(){ return e1Label; }
    public JLabel getE2Label(){ return e2Label; }
    public JLabel getE3Label(){ return e3Label; }
    public JLabel getF1Label(){ return f1Label; }
    public JLabel getF2Label(){ return f2Label; }
    public JLabel getF3Label(){ return f3Label; }
    public JLabel getG1Label(){ return g1Label; }
    public JLabel getG2Label(){ return g2Label; }
    public JLabel getG3Label(){ return g3Label; }
    
    public JLabel getP1Label(){ return p1Label; }
    public JLabel getP2Label(){ return p2Label; }
    public JLabel getP3Label(){ return p3Label; }
    public JLabel getP4Label(){ return p4Label; }
    public JLabel getP5Label(){ return p5Label; }
    public JLabel getP6Label(){ return p6Label; }
    public JLabel getP7Label(){ return p7Label; }
    public JLabel getP8Label(){ return p8Label; }
    public JLabel getP9Label(){ return p9Label; }
    
    public JButton getEnviarButton() { return enviarButton; }
    public JButton getIniciarJogoButton(){ return iniciarJogoButton; }
    public JButton getReiniciarJogoButton() { return reiniciarJogoButton; }
    public JButton getVoltarJogoButton() { return voltarJogoButton; }
    public JButton getDesistirJogoButton() { return desistirJogoButton; }
    
    public JLabel getStatusJogoLabel(){ return statusJogoLabel; }
    public JLabel getSelecaoPecaLabel() { return selecaPecaLabel; }
    public JTextArea getConversaTextArea(){ return conversaTextArea; }
    public JTextField getMensagemTextField() { return mensagemTextField; }
}
